site_name: {{ cookiecutter.project_name }}
# # {% if cookiecutter.author_name %}
# site_author: {{ cookiecutter.author_name }}
# # {% endif %}
nav:
  - Home: index.md
  - Experiments: models.md
theme: readthedocs